#pragma once

// ds_vk/pch.hpp
#include <SDL3/SDL.h>                    // IWYU pragma: keep
#include <SDL3/SDL_vulkan.h>             // IWYU pragma: keep
#include <algorithm>                     // IWYU pragma: keep
#include <array>                         // IWYU pragma: keep
#include <chrono>                        // IWYU pragma: keep
#include <cmath>                         // IWYU pragma: keep
#include <bit>                           // IWYU pragma: keep
#include <charconv>                      // IWYU pragma: keep
#include <cstddef>                       // IWYU pragma: keep
#include <cstdint>                       // IWYU pragma: keep
#include <cstring>                       // IWYU pragma: keep
#include <filesystem>                    // IWYU pragma: keep
#include <format>                        // IWYU pragma: keep
#include <fstream>                       // IWYU pragma: keep
#include <glm/glm.hpp>                   // IWYU pragma: keep
#include <glm/gtc/matrix_transform.hpp>  // IWYU pragma: keep
#include <glm/gtc/type_ptr.hpp>          // IWYU pragma: keep
#include <imgui.h>                       // IWYU pragma: keep
#include <imgui_impl_sdl3.h>             // IWYU pragma: keep
#include <imgui_impl_vulkan.h>           // IWYU pragma: keep
#include <iostream>                      // IWYU pragma: keep
#include <limits>                        // IWYU pragma: keep
#include <map>                           // IWYU pragma: keep
#include <memory>                        // IWYU pragma: keep
#include <numbers>                       // IWYU pragma: keep
#include <optional>                      // IWYU pragma: keep
#include <print>                         // IWYU pragma: keep
#include <ranges>                        // IWYU pragma: keep
#include <span>                          // IWYU pragma: keep
#include <stdexcept>                     // IWYU pragma: keep
#include <string>                        // IWYU pragma: keep
#include <string_view>                   // IWYU pragma: keep
#include <unordered_map>                 // IWYU pragma: keep
#include <unordered_set>                 // IWYU pragma: keep
#include <utility>                       // IWYU pragma: keep
#include <vector>                        // IWYU pragma: keep
#include <vk_mem_alloc.h>                // IWYU pragma: keep
#include <vulkan/vulkan.h>               // IWYU pragma: keep
